language: scala
scala:
- 2.11.6
jdk:
- oraclejdk8
before_install: unset SBT_OPTS JVM_OPTS
script:
- sbt compile
- ./activator dist
- ls
cache: 
  directories:
  - target
  - project
  - $HOME/.ivy2/cache
  - $HOME/.sbt/