language: scala
scala:
- 2.11.6
jdk:
- oraclejdk8
before_install: unset SBT_OPTS JVM_OPTS
script:
- chmod ugo+x activator
- ./activator compile
- ./activator dist
- ls
cache: 
  directories:
  - project
  - $HOME/.ivy2/cache
  - $HOME/.sbt/