language: scala
scala:
- 2.11.6
jdk:
- oraclejdk8
script:
- sbt compile
- ./activator dist
- ls
cache: 
  directories:
  - target
  - project
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION